misc {
    vrr = 1
}

general {
    gaps_in = 5
    gaps_out = 12
    border_size = 1
    col.active_border = rgba(ffffff15)
    col.inactive_border = rgba(00000010)
    layout = dwindle
}

decoration {
    rounding = 12

    shadow {
        enabled = true
        range = 25
        render_power = 4
        color = rgba(00000040)
    }

    blur {
        enabled = true
        size = 5
        passes = 3
        brightness = 0.8
        vibrancy = 0.16
    }
}

windowrule {
    name = windowrule-1
    float = on
    size = 450 600
    move = ((monitor_w*0.7)) (50)
    match:class = (pavucontrol)
}

windowrule {
    name = windowrule-2
    float = on
    size = 450 600
    move = ((monitor_w*0.65)) (50)
    match:class = (blueman-manager)
}

windowrule {
    name = windowrule-3
    float = on
    size = 450 600
    move = ((monitor_w*0.6)) (50)
    match:class = (nm-connection-editor)
}

windowrule {
    name = windowrule-4
    float = true
    size = 900 600
    center = true
    match:class = Alacritty
}

windowrule {
    name = windowrule-5
    opacity = 0.6 0.6
    match:class = Nautilus
}

animations {
    enabled = yes

    bezier = macOS, 0.25, 1, 0.5, 1
    bezier = workspaceBounce, 0.2, 1.1, 0.3, 1.05

    animation = windows, 1, 4, macOS, popin 85%
    animation = windowsOut, 1, 4, macOS, popin 85%
    animation = windowsMove, 1, 4, macOS

    animation = workspaces, 1, 4, macOS, fade
    animation = border, 1, 3, default
    animation = fade, 0
}

$mainMod = SUPER
bind = $mainMod, Z, exec, alacritty
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, nautilus
bind = $mainMod, V, togglefloating,
bind = $mainMod, Tab, exec, rofi -show drun
bind = $mainMod, P, pseudo,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, M, fullscreen, 1

bind = $mainMod, right, workspace, r+1
bind = $mainMod, left, workspace, r-1

bind = $mainMod ALT, right, movetoworkspace, r+1
bind = $mainMod ALT, left, movetoworkspace, r-1

bind = $mainMod, Print, exec, grim -g "$(slurp)" - | wl-copy

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod SHIFT, M, exit,
bind = $mainMod, X, exec, wlogout

binde = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

windowrule {
    name = windowrule-6
    float = on
    size = 600 450
    move = ((monitor_w*0.68)) (monitor_h*0.50)
    match:title = tui_menu
}

windowrule {
    name = gnome-calendar-scratchpad
    float = on
    size = 800 0
    move = ((monitor_w*0.30)) (monitor_h*0.69)
    animation = slide bottom
    match:class = ^(org.gnome.Calendar)$
}

layerrule {
    name = layerrule-1
    blur = on
    ignore_alpha = 0
    match:namespace = waybar
}

windowrule {
    name = windowrule-7
    float = on
    size = 800 500
    move = (center)
    match:title = ^(tui_calendar)$
}
