#SHARED PARTS
source = ~/.config/hypr/shared/shared_hypr.conf
source = ~/.config/hypr/shared/dark_theme.conf

#MAIN ONES
source = ~/.config/hypr/desktop/input.conf
source = ~/.config/hypr/desktop/monitors.conf
source = ~/.config/hypr/desktop/startup.conf
source = ~/.config/hypr/desktop/wallpaper.conf
