# --- APPS DE SISTEMA ---
exec-once = swaync
# exec-once = flatpak run com.github.wwmm.easyeffects
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = systemctl --user start hyprpolkitagent
exec-once = steam
exec-once = openrgb --startminimized -p WhiteProfile
exec-once = sleep 1 && waybar
