#SHARED PARTS
source = ~/.config/hypr/shared/shared_hypr.conf
source = ~/.config/hypr/shared/dark_theme.conf

#MAIN ONES
source = ~/.config/hypr/laptop/input.conf
source = ~/.config/hypr/laptop/monitors.conf
source = ~/.config/hypr/laptop/startup.conf
source = ~/.config/hypr/laptop/wallpaper.conf
