# --- CONFIGURAÇÃO DO WALLPAPER ENGINE (DUAL SCREEN) ---

# Configurações Monitor Principal (Direita - HDMI)
$screen1  = HDMI-A-1
$wall_id1 = 2590421912

# Configurações Monitor Secundário (Esquerda - DP-1)
$screen2  = DP-1
$wall_id2 = 3483522894

# Definições Globais
$scaling = fill
$fps     = 30

# Execução para o Monitor 1 (HDMI)
exec-once = linux-wallpaperengine --screen-root $screen1 --bg $wall_id1 --scaling $scaling --clamp border --fps $fps --no-fullscreen-pause --silent

# Execução para o Monitor 2 (DP-1)
exec-once = linux-wallpaperengine --screen-root $screen2 --bg $wall_id2 --scaling $scaling --clamp border --fps $fps --no-fullscreen-pause --silent
